version: '3.4'

services:
  postgresqlUser:
    image: postgres
    container_name: postgresqlUser
    restart: always
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresqlUser/data

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgresqlUser;Port=5432;Database=userservice;Username=postgres;Password=toor"
    depends_on:
      - postgresqlUser
    ports:
      - "5047:5047"

volumes:
  postgres_data:
    driver: local

